
package view_QLSV;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import model.SinhVien;
import model.diemSV;
import model.ds_diemSV;
import model.monHoc;

/**
 *
 * @author fpt
 */
public class view extends javax.swing.JFrame {
    private List<diemSV> ds  = new ArrayList();
    viewdiem viewdiem = new viewdiem();
    /**
     * Creates new form view
     */
     private JFileChooser ofc;
    private JFileChooser ifc;
        int index=1;
   
    
    public void docfile(String name) throws IOException, ClassNotFoundException{
        
        
        
            
        ObjectInputStream oos = null;
        try {
            oos = new ObjectInputStream(new FileInputStream(new File("C:\\Users\\fpt\\OneDrive\\Máy tính\\"+name)));
            this.ds = (ArrayList<diemSV>) oos.readObject();
            System.out.println("Success...");
        } catch (IOException ex) {
            ex.printStackTrace();
        } finally {
            oos.close();
        }
    }
    
    public void luuSinhVien(String name) throws IOException{
        ObjectOutputStream oos = null;
        
        
        try {
        
            oos = new ObjectOutputStream(new FileOutputStream(new File("C:\\Users\\fpt\\OneDrive\\Máy tính\\"+name+".txt")));
            oos.writeObject(ds);
            System.out.println("Success...");
            JOptionPane.showMessageDialog(null,"Đã lưu file.");
        } catch (IOException ex) {
            ex.printStackTrace();
        } finally {
            oos.close();
        }
    }
    
    public view() {
       
        initComponents();
        
        setLocationRelativeTo(null);
        ofc = new JFileChooser();
        ifc = new JFileChooser();
        ifc.setCurrentDirectory(new File("C:\\Users\\admin\\Documents\\NetBeansProjects\\GiuaKyPart2"));
        ofc.setCurrentDirectory(new File("C:\\Users\\admin\\Documents\\NetBeansProjects\\GiuaKyPart2"));       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        btn_sortname = new javax.swing.JButton();
        btn_sortGPA = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField_timma = new javax.swing.JTextField();
        jTextField_timten = new javax.swing.JTextField();
        btn_findmaSV = new javax.swing.JButton();
        btn_findname = new javax.swing.JButton();
        jButton_tinh = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField_maSV = new javax.swing.JTextField();
        jTextField_nhapten = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jComboBox_que2 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField_ngaysinh = new javax.swing.JTextField();
        jTextField_gioitinh = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btn_themSV = new javax.swing.JButton();
        XoaSV = new javax.swing.JButton();
        btn_lammoi = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jTextField_Mamon = new javax.swing.JTextField();
        jTextField_tenMonhoc = new javax.swing.JTextField();
        jTextField_soTinchi = new javax.swing.JTextField();
        jTextField_nhapdiem = new javax.swing.JTextField();
        jTextField_nhapMaSV = new javax.swing.JTextField();
        btn_luudiem = new javax.swing.JButton();
        btn_bangdiem = new javax.swing.JButton();
        btn_sua = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton_lammoidiem = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btn_open_File = new javax.swing.JMenuItem();
        btn_Save_file = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Quê quán:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "An Giang", "Bà Rịa – Vũng Tàu", "Bạc Liêu", "Bắc Giang", "Bắc Kạn", "Bắc Ninh", "Bến Tre", "Bình Dương", "Bình Định", "Bình Phước", "Bình Thuận", "Cà Mau", "Cao Bằng", "Cần Thơ", "Đà Nẵng", "Đắk Lắk", "Đắk Nông", "Điện Biên", "Đồng Nai", "Đồng Tháp", "Gia Lai", "Hà Giang", "Hà Nam", "Hà Nội", "Hà Tĩnh", "Hải Dương", "Hải Phòng", "Hậu Giang", "Hòa Bình", "Thành phố Hồ Chí Minh", "Hưng Yên", "Khánh Hòa", "Kiên Giang", "Kon Tum", "Lai Châu", "Lạng Sơn", "Lào Cai", "Lâm Đồng", "Long An", "Nam Định", "Nghệ An", "Ninh Bình", "Ninh Thuận", "Phú Thọ", "Phú Yên", "Quảng Bình", "Quảng Nam", "Quảng Ngãi", "Quảng Ninh", "Quảng Trị", "Sóc Trăng", "Sơn La", "Tây Ninh", "Thái Bình", "Thái Nguyên", "Thanh Hóa", "Thừa Thiên Huế", "Tiền Giang", "Trà Vinh", "Tuyên Quang", "Vĩnh Long", "Vĩnh Phúc", "Yên Bái" }));
        jComboBox1.setToolTipText("");
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        btn_sortname.setText("Sắp xếp theo tên");
        btn_sortname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sortnameActionPerformed(evt);
            }
        });

        btn_sortGPA.setText("Sắp xếp theo GPA");
        btn_sortGPA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sortGPAActionPerformed(evt);
            }
        });

        jLabel2.setText("Nhập Mã SV");

        jLabel3.setText("Nhập Tên SV");

        btn_findmaSV.setText("Tìm mã");
        btn_findmaSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_findmaSVActionPerformed(evt);
            }
        });

        btn_findname.setText("Tìm tên");
        btn_findname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_findnameActionPerformed(evt);
            }
        });

        jButton_tinh.setText("Tìm");
        jButton_tinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_tinhActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_sortname)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_sortGPA))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addComponent(jButton_tinh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 182, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_timma, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_timten, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(116, 116, 116)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_findmaSV)
                    .addComponent(btn_findname))
                .addGap(49, 49, 49))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_timma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_findmaSV)
                    .addComponent(jButton_tinh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_sortname)
                    .addComponent(btn_sortGPA)
                    .addComponent(jLabel3)
                    .addComponent(jTextField_timten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_findname))
                .addContainerGap())
        );

        jLabel4.setText("Bảng điểm sinh viên:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã SV", "Họ Và Tên", "Ngày sinh", "Giới tính", "Quê quán", "GPA"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel5.setText("Thông tin sinh viên.");

        jLabel6.setText("Mã sinh viên :");

        jTextField_maSV.setText("Nhập mã SV");

        jTextField_nhapten.setText("Nhập tên");

        jLabel7.setText("Tên sinh viên :");

        jComboBox_que2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "An Giang", "Bà Rịa – Vũng Tàu", "Bạc Liêu", "Bắc Giang", "Bắc Kạn", "Bắc Ninh", "Bến Tre", "Bình Dương", "Bình Định", "Bình Phước", "Bình Thuận", "Cà Mau", "Cao Bằng", "Cần Thơ", "Đà Nẵng", "Đắk Lắk", "Đắk Nông", "Điện Biên", "Đồng Nai", "Đồng Tháp", "Gia Lai", "Hà Giang", "Hà Nam", "Hà Nội", "Hà Tĩnh", "Hải Dương", "Hải Phòng", "Hậu Giang", "Hòa Bình", "Thành phố Hồ Chí Minh", "Hưng Yên", "Khánh Hòa", "Kiên Giang", "Kon Tum", "Lai Châu", "Lạng Sơn", "Lào Cai", "Lâm Đồng", "Long An", "Nam Định", "Nghệ An", "Ninh Bình", "Ninh Thuận", "Phú Thọ", "Phú Yên", "Quảng Bình", "Quảng Nam", "Quảng Ngãi", "Quảng Ninh", "Quảng Trị", "Sóc Trăng", "Sơn La", "Tây Ninh", "Thái Bình", "Thái Nguyên", "Thanh Hóa", "Thừa Thiên Huế", "Tiền Giang", "Trà Vinh", "Tuyên Quang", "Vĩnh Long", "Vĩnh Phúc", "Yên Bái" }));

        jLabel8.setText("Quê quán");

        jLabel9.setText("Ngày Sinh :");

        jTextField_ngaysinh.setText("nhập ngày sinh");

        jTextField_gioitinh.setText("Nhập giới tính");

        jLabel11.setText("Giới tính :");

        btn_themSV.setText("Thêm SV");
        btn_themSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themSVActionPerformed(evt);
            }
        });

        XoaSV.setText("Xóa SV");
        XoaSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XoaSVActionPerformed(evt);
            }
        });

        btn_lammoi.setText("Làm mới");
        btn_lammoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lammoiActionPerformed(evt);
            }
        });

        btn_update.setText("Cập nhật");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        jLabel23.setText("Nhập điểm SV");

        jLabel24.setText("Nhập mã môn");

        jLabel25.setText("Nhập tên môn học");

        jLabel26.setText("Nhập số tín chỉ");

        jLabel27.setText("Nhập điểm");

        jLabel28.setText("Nhập mã SV ");

        jTextField_Mamon.setText("Nhập mã môn");

        jTextField_tenMonhoc.setText("Nhập tên");

        jTextField_soTinchi.setText("Nhập số tín");

        jTextField_nhapdiem.setText("Nhập điểm");

        jTextField_nhapMaSV.setText("Nhập mã SV");

        btn_luudiem.setText("Lưu điểm");
        btn_luudiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_luudiemActionPerformed(evt);
            }
        });

        btn_bangdiem.setText("Bảng điểm");
        btn_bangdiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bangdiemActionPerformed(evt);
            }
        });

        btn_sua.setText("Sửa TT");
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });

        jButton1.setText("Reload data");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton_lammoidiem.setText("Làm mới");
        jButton_lammoidiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_lammoidiemActionPerformed(evt);
            }
        });

        jButton2.setText("Xoá theo mã môn");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        btn_open_File.setText("Open");
        btn_open_File.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_open_FileActionPerformed(evt);
            }
        });
        jMenu1.add(btn_open_File);

        btn_Save_file.setText("Save");
        btn_Save_file.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Save_fileActionPerformed(evt);
            }
        });
        jMenu1.add(btn_Save_file);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField_nhapten)
                                    .addComponent(jComboBox_que2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField_ngaysinh)
                                    .addComponent(jTextField_gioitinh)))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jTextField_maSV, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(119, 119, 119)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn_update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(XoaSV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_lammoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_sua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_themSV)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                            .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_Mamon, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(jTextField_tenMonhoc)
                            .addComponent(jTextField_nhapdiem)
                            .addComponent(jTextField_soTinchi, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(jTextField_nhapMaSV))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btn_bangdiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_luudiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_lammoidiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(53, 53, 53))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel23))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField_maSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel24)
                        .addComponent(jTextField_Mamon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_themSV)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton_lammoidiem)
                        .addGap(10, 10, 10))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel25)
                                    .addComponent(jTextField_tenMonhoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_lammoi)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(jTextField_nhapten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(1, 1, 1)))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jTextField_soTinchi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_luudiem)
                    .addComponent(jComboBox_que2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(XoaSV))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jTextField_nhapdiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_bangdiem)
                    .addComponent(jTextField_ngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(btn_sua))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField_gioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28)
                    .addComponent(jTextField_nhapMaSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_update)
                    .addComponent(jButton2))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_Save_fileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Save_fileActionPerformed
        if(evt.getSource() == btn_Save_file){
            int result = ifc.showSaveDialog(this);
            if(result == JFileChooser.APPROVE_OPTION){
                File res = ifc.getSelectedFile();
                System.out.println("Save as file: " + res.getAbsolutePath());

                try {
                    luuSinhVien(res.getName());
                } catch (IOException ex) {
                    Logger.getLogger(view.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_btn_Save_fileActionPerformed

    private void btn_themSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themSVActionPerformed
        if(!jTextField_maSV.equals("") && !jTextField_gioitinh.equals("") &&! jTextField_nhapten.equals("")){
           thembangdiem();
            
        }
    }//GEN-LAST:event_btn_themSVActionPerformed

    private void btn_luudiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_luudiemActionPerformed
        if(!jTextField_Mamon.equals("") && !jTextField_soTinchi.equals("") &&! jTextField_tenMonhoc.equals("") && !jTextField_nhapMaSV.equals("")){
            themdiemmonhoc();
        }
    }//GEN-LAST:event_btn_luudiemActionPerformed
    
    private void btn_sortnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sortnameActionPerformed
         sapxepten();
         lammoibang();
    }//GEN-LAST:event_btn_sortnameActionPerformed

    private void btn_lammoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lammoiActionPerformed
        // TODO add your handling code here:
        xoaForm();
    }//GEN-LAST:event_btn_lammoiActionPerformed

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
        suaTT();
    }//GEN-LAST:event_btn_suaActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int t = jTable1.getSelectedRow();
        jTextField_nhapMaSV.setText((String) model.getValueAt(t,1));
    }//GEN-LAST:event_jTable1MouseClicked

    private void XoaSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XoaSVActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int t = jTable1.getSelectedRow();
        String id =  (String) jTable1.getValueAt(t,1);
        diemSV xoasv = timtheoma(id);
        this.ds.remove(xoasv);
        model.getDataVector().removeAllElements();
        
        for(diemSV d:ds){
            index=1;
            model.addRow(new Object[]{String.valueOf(index++),d.getMaSV(),d.getTenSV(),d.getNgaySinh(),d.getGioitinhSV(),d.getDiachiSV(),String.valueOf(d.getGPA())});
        }
    }//GEN-LAST:event_XoaSVActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        update();
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_sortGPAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sortGPAActionPerformed
        sapxeptheoGPA();
        lammoibang();
    }//GEN-LAST:event_btn_sortGPAActionPerformed

    private void btn_findmaSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_findmaSVActionPerformed
        timtheoma();
    }//GEN-LAST:event_btn_findmaSVActionPerformed

    private void btn_findnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_findnameActionPerformed
        timtheoten();
    }//GEN-LAST:event_btn_findnameActionPerformed

    private void btn_open_FileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_open_FileActionPerformed
      if(evt.getSource() == btn_open_File){
            int result = ofc.showOpenDialog(this);
            if(result == JFileChooser.APPROVE_OPTION){
                String name = ofc.getSelectedFile().getName();
                try {
                    docfile(name);
                    lammoibang();
                } catch (IOException ex) {
                    Logger.getLogger(view.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(view.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
        }
    }//GEN-LAST:event_btn_open_FileActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton_tinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_tinhActionPerformed
        if(!jComboBox1.getItemAt(jComboBox1.getSelectedIndex()).equals("Tất cả")){
            lammoibang();
            loctheotinh();
            
        }
        else lammoibang();
    }//GEN-LAST:event_jButton_tinhActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        lammoibang();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton_lammoidiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_lammoidiemActionPerformed
        jTextField_Mamon.setText("");
        jTextField_nhapMaSV.setText("");
        jTextField_nhapdiem.setText("");
        jTextField_tenMonhoc.setText("");
        jTextField_soTinchi.setText("");
    }//GEN-LAST:event_jButton_lammoidiemActionPerformed

    private void btn_bangdiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bangdiemActionPerformed
         
         viewdiem.setTitle("Bảng điểm");
         viewdiem.setSize(500,500);
         viewdiem.setLocationRelativeTo(null);
         ghidiem();
         viewdiem.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
         viewdiem.setVisible(true);
    }//GEN-LAST:event_btn_bangdiemActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        xoatheomamon();
        
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
 
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new view().setVisible(true);
               
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton XoaSV;
    private javax.swing.JMenuItem btn_Save_file;
    private javax.swing.JButton btn_bangdiem;
    private javax.swing.JButton btn_findmaSV;
    private javax.swing.JButton btn_findname;
    private javax.swing.JButton btn_lammoi;
    private javax.swing.JButton btn_luudiem;
    private javax.swing.JMenuItem btn_open_File;
    private javax.swing.JButton btn_sortGPA;
    private javax.swing.JButton btn_sortname;
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_themSV;
    private javax.swing.JButton btn_update;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton_lammoidiem;
    private javax.swing.JButton jButton_tinh;
    private javax.swing.JComboBox<String> jComboBox1;
    public javax.swing.JComboBox<String> jComboBox_que2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField_Mamon;
    public javax.swing.JTextField jTextField_gioitinh;
    public javax.swing.JTextField jTextField_maSV;
    public javax.swing.JTextField jTextField_ngaysinh;
    private javax.swing.JTextField jTextField_nhapMaSV;
    private javax.swing.JTextField jTextField_nhapdiem;
    public javax.swing.JTextField jTextField_nhapten;
    private javax.swing.JTextField jTextField_soTinchi;
    private javax.swing.JTextField jTextField_tenMonhoc;
    private javax.swing.JTextField jTextField_timma;
    private javax.swing.JTextField jTextField_timten;
    // End of variables declaration//GEN-END:variables

    private void xoaForm() {
        jTextField_gioitinh.setText("");
        jTextField_ngaysinh.setText("");
        jTextField_nhapten.setText("");
        jTextField_maSV.setText("");
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void thembangdiem() {
        int ok=1;
        for(diemSV x:ds){
            if(x.getMaSV().equals(jTextField_maSV.getText()) || ds.isEmpty()){
                ok=0;
                break;
            }
                
        }
        if(ok == 1){
            diemSV a = new diemSV();
            a.setGioitinhSV(jTextField_gioitinh.getText());
            
            String x = String.valueOf(jComboBox_que2.getItemAt(jComboBox_que2.getSelectedIndex()));
            a.setDiachiSV(x);
            a.setMaSV(jTextField_maSV.getText());
            a.setTenSV(jTextField_nhapten.getText());
            a.setNgaySinh(jTextField_ngaysinh.getText());
            this.ds.add(a);
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        
        model.addRow(new Object[]{String.valueOf(index++),a.getMaSV(),a.getTenSV(),a.getNgaySinh(),a.getGioitinhSV(),a.getDiachiSV(),String.valueOf(a.getGPA())});
        
        }
        else {
            JOptionPane.showMessageDialog(null, "Trùng mã sinh viên!");
            ok=0;
        }
//throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void suaTT() {
        
        
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int t = jTable1.getSelectedRow();
        jComboBox_que2.setSelectedItem((String) model.getValueAt(t,6));
        jTextField_gioitinh.setText((String) model.getValueAt(t,4));
        jTextField_ngaysinh.setText((String) model.getValueAt(t,3));
        jTextField_nhapten.setText((String) model.getValueAt(t,2));
        jTextField_maSV.setText((String) model.getValueAt(t,1));
        
        
        
        

        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void themdiemmonhoc() {
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int t = jTable1.getSelectedRow();
        jTextField_nhapMaSV.setText((String) model.getValueAt(t,1));
        
        
        monHoc monhoc = new monHoc((String)jTextField_Mamon.getText(),(String)jTextField_tenMonhoc.getText(),Integer.valueOf(jTextField_soTinchi.getText()),Double.valueOf(jTextField_nhapdiem.getText()));
                diemSV sv = timtheoma(jTextField_nhapMaSV.getText());
               sv.suatheomamon(jTextField_Mamon.getText(),Double.valueOf(jTextField_nhapdiem.getText()), monhoc,Integer.valueOf(jTextField_soTinchi.getText()));
               
               String x = String.valueOf(sv.getGPA());
               jTable1.setValueAt(x, t,6);
               JOptionPane.showMessageDialog(null,"Đã lưu điểm môn học.");
         
       
    }
    public diemSV timtheoma(String id){
        for(diemSV d : ds){
            if(id.equals(d.getMaSV()))
                return d;
            
        }
        return null;
    }
    public diemSV timtheomabl(String id){
        for(diemSV d : ds){
            if(id.equals(d.getMaSV()))
                return d;
            break;
        }
        return null;
    }

    private void update() {
        DefaultTableModel model1 = (DefaultTableModel) jTable1.getModel();
        int t = jTable1.getSelectedRow();
        String id =  (String) jTable1.getValueAt(t,1);
        diemSV suasv = timtheoma(id);
        suasv.setTenSV(jTextField_nhapten.getText());
       model1.setValueAt(suasv.getTenSV(), t,2); 
        suasv.setNgaySinh(jTextField_ngaysinh.getText());
         model1.setValueAt(suasv.getNgaySinh(), t,3); 
        suasv.setGioitinhSV(jTextField_gioitinh.getText());
        suasv.setDiachiSV(jComboBox_que2.getItemAt(jComboBox_que2.getSelectedIndex()));                                                             
        model1.setValueAt(suasv.getGioitinhSV(), t,4);       
        model1.setValueAt(suasv.getDiachiSV(), t,5);
        JOptionPane.showMessageDialog(null, "Đã cập nhật thông tin Sinh viên.");
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void sapxepten() {
        JOptionPane.showMessageDialog(null, "Bảng đã được sắp sếp.");
        Collections.sort(ds, (o1, o2) -> {
            return o1.getTenSV().compareTo(o2.getTenSV()); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/LambdaBody
        }
        );


        // throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void lammoibang() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.getDataVector().removeAllElements();
        index=1;
        for(diemSV d:ds){
            
            model.addRow(new Object[]{String.valueOf(index++),d.getMaSV(),d.getTenSV(),d.getNgaySinh(),d.getGioitinhSV(),d.getDiachiSV(),String.valueOf(d.getGPA())});
        }
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void sapxeptheoGPA() {
        JOptionPane.showMessageDialog(null, "Bảng đã được sắp sếp.");
       Collections.sort(ds,new Comparator<diemSV>(){
           @Override
           public int compare(diemSV o1,diemSV o2){
               if(o1.getGPA()>o2.getGPA()) return 1;
               else if(o1.getGPA()==o2.getGPA()) return 0;
               return -1;
           }
       }
       
       );

        // throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void timtheoma() {
        String s = jTextField_timma.getText();
        DefaultTableModel model2 = (DefaultTableModel) jTable1.getModel();
        model2.getDataVector().removeAllElements();
        index=1;
        for(diemSV d: ds){
            
            if(d.getMaSV().equals(s)) {
                 model2.addRow(new Object[]{String.valueOf(index++),d.getMaSV(),d.getTenSV(),d.getNgaySinh(),d.getGioitinhSV(),d.getDiachiSV(),String.valueOf(d.getGPA())});
                 
            }
        }
        if(s.equals("")){
            index=1;
            for(diemSV d:ds){
                
               model2.addRow(new Object[]{String.valueOf(index++),d.getMaSV(),d.getTenSV(),d.getNgaySinh(),d.getGioitinhSV(),d.getDiachiSV(),String.valueOf(d.getGPA())});

            }
        }
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void timtheoten() {
        DefaultTableModel m = (DefaultTableModel) jTable1.getModel();
        m.getDataVector().removeAllElements();
        String ten = jTextField_timten.getText();
        index=1;
        for(diemSV d:ds){
            
            if(d.getTenSV().equals(ten)){
                m.addRow(new Object[]{String.valueOf(index++),d.getMaSV(),d.getTenSV(),d.getNgaySinh(),d.getGioitinhSV(),d.getDiachiSV(),String.valueOf(d.getGPA())});
        }
        }
        if(ten.equals("")){
            index=1;
            for(diemSV d:ds){
                m.addRow(new Object[]{String.valueOf(index++),d.getMaSV(),d.getTenSV(),d.getNgaySinh(),d.getGioitinhSV(),d.getDiachiSV(),String.valueOf(d.getGPA())});

            }

        }
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void loctheotinh() {
        DefaultTableModel model2 = (DefaultTableModel) jTable1.getModel();
        model2.getDataVector().removeAllElements();
       
        for(diemSV d: ds){
            index=1;
            if(d.getDiachiSV().equals(jComboBox1.getItemAt(jComboBox1.getSelectedIndex()))) {
                 model2.addRow(new Object[]{String.valueOf(index++),d.getMaSV(),d.getTenSV(),d.getNgaySinh(),d.getGioitinhSV(),d.getDiachiSV(),String.valueOf(d.getGPA())});
                 
            }
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    }
    public diemSV timtheomaSV(String id){
        for(diemSV x: ds){
            if(x.getMaSV().equals(id)){
                return x;
                
            }
        }
        return null;
    }
    private void ghidiem() {
        
        String id = jTextField_nhapMaSV.getText();
        DefaultTableModel model2 = (DefaultTableModel) viewdiem.jTable1.getModel();
        model2.getDataVector().removeAllElements();
        diemSV sv = timtheoma(id);
        for(monHoc x: sv.getList_Monhoc()){
            model2.addRow(new Object[]{String.valueOf(x.getMaMonhoc()),String.valueOf(x.getTenmonhoc()),String.valueOf(x.getSoTinchi()),String.valueOf(x.getDiem())});
        }
        
        
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    private void xoatheomamon(){
        String id = jTextField_nhapMaSV.getText();
        int ok=0;
        diemSV x = timtheomaSV(id);
                if(x.timmamon(jTextField_Mamon.getText())){
                    x.xoatheomaMonhoc(jTextField_Mamon.getText());
                    ghidiem();
                ok=1;
                int t = jTable1.getSelectedRow();
                String u = String.valueOf(x.getGPA());
               jTable1.setValueAt(u, t,6);
               
                JOptionPane.showMessageDialog(null,"Đã xóa theo mã môn. ");
                }
                else{
                    ok=1;
                    JOptionPane.showMessageDialog(null,"Mã môn không hợp lệ.  ");
                }
            
        
        if(ok==0){
            JOptionPane.showMessageDialog(null,"Mã sinh viên không đúng.");
        }
    }
}
